### ISSUE TITLE
Search results show "news" posts incorrectly

### ISSUE THREAD

**Issue by teacher-svb** [vsoch/docsy-jekyll#13]
e.g. if you search for "welcome" one of the search results (the one referring to the "Welcome to MkDocs Jekyll" news post) will have no title or clickable link, with html markup visible in the following text.

This is true for all news posts.

**Comment by vsoch** [comment]
Taking a look!

**Comment by vsoch** [comment]
okay reproduced, I think this is what you are referring to:

![image](https://user-images.githubusercontent.com/814322/72290653-f4089f00-360a-11ea-8557-d7b516fc8b22.png)

**Comment by vsoch** [comment]
okay - I have a branch for you to test! https://github.com/vsoch/docsy-jekyll/pull/14 Let me know if everything looks okay, and we can merge.

**Comment by teacher-svb** [comment]
Yep, everythings fixed! (wow, that was a fast reply... :-D )
