### ISSUE TITLE
404'd from Getting Started

### ISSUE THREAD

**Issue by alexstorer** [vsoch/docsy-jekyll#16]
If you click on this link:
![image](https://user-images.githubusercontent.com/1117678/76116973-c18e7900-5f9f-11ea-8d72-1a8c850d8724.png)

**Comment by vsoch** [comment]
Doh! Looks like the baseurl was missing from the breadcrumb, thank you for finding this! I've just pushed a fix (and it closed it automatically since I referenced the issue) so when GitHub pages rebuilds (and make sure your cache is not being used) the issue should be resolved.

**Comment by vsoch** [comment]
okay looks good for me now - you can open devtools and check the box to make sure the cache isn't used when it's open (or open new window/tab, whatever your preference for not using the cache) and check to see that it's fixed.
