### ISSUE TITLE
Top level link missing in breadcrumb

### ISSUE THREAD

**Issue by gunhansancar** [vsoch/docsy-jekyll#18]
Breadcrumbs are missing the top level link. Currently it just links to the same page which doesn't helpful for the user.

Expected behaviour:
Documentation > Get Started
I.e.: https://example.docsy.dev/docs/getting-started/

Actual behaviour:
Get Started
I.e.: https://vsoch.github.io/docsy-jekyll/docs/getting-started

**Comment by vsoch** [comment]
Ah okay - so you would want the first level (the link back to Documentation) added?

**Comment by vsoch** [comment]
hey @gunhansancar could you please make sure your browser isn't caching (either new tab / open up devtools and refresh the page) and look now at https://vsoch.github.io/docsy-jekyll/ to see if it's to your liking? If so, I'll draft a new release with the fix. Thanks!

**Comment by gunhansancar** [comment]
Thanks for your prompt response 👍 . It looks better now. It suits for my needs. 

Though when there are multiple levels it doesn't support that
I.e.
https://example.docsy.dev/docs/tutorials/multi-bear/

Ideally, it should go deeper if the parent node has parent as well. Like a recursive fashion.

**Comment by vsoch** [comment]
That's a bug! Please take another look now.

**Comment by gunhansancar** [comment]
Thanks for your help. I think it works well now. 👍
