### ISSUE TITLE
~~Windows can't use docsy-jekyll~~ jquery can't be loaded in China

### ISSUE THREAD

**Issue by puppylpg** [vsoch/docsy-jekyll#25]
Hi,
Thanks for docsy-jekyll. 
I run it on Windows Subsystem Linux, and it works. However when I open the website by chrome, the response is too slow to bare. At the same time, toc in the right sidebar doesn't appear. When I run it on Linux, everything is ok. So I thought it may be caused by WSL.
Interesting thing happens: I deploy [it](https://github.com/puppylpg/puppylpg.github.io) to [github pages](https://puppylpg.github.io/2020/08/18/micrometer/), then the same problem arises when visiting using Windows chrome(slow & no toc in the right sidebar). At the same time, vising using Linux chrome is totally ok.
Any idea what happens? 
Thanks in advance.

**Comment by vsoch** [comment]
I don’t use Windows so I can’t debug more do I have an idea. But I’d suggest testing other Jekyll sites, if others are slow it’s likely a Windows Jekyll issue. You could also look in the bowser console for warnings. Anyway if you do figure out the issue please contribute a PR to fix!

**Comment by vsoch** [comment]
Oh, and I’ll also check to see if standard docsy (deployed with Hugo) is also slow for you. It’s just a static site, so I’m not sure what Windows is having trouble with... perhaps look at the networking box in the browser console and figure out what specifically is causing the slowness?

**Comment by puppylpg** [comment]
> I don’t use Windows so I can’t debug nor do I have an idea. But I’d suggest testing other Jekyll sites, if others are slow it’s likely a Windows Jekyll issue. You could also look in the browser console for warnings. Anyway if you do figure out the issue please contribute a PR to fix!

Other jekyll theme is ok because I use jekyll theme minima before, everything is ok.

**Comment by puppylpg** [comment]
> > I don’t use Windows so I can’t debug nor do I have an idea. But I’d suggest testing other Jekyll sites, if others are slow it’s likely a Windows Jekyll issue. You could also look in the browser console for warnings. Anyway if you do figure out the issue please contribute a PR to fix!
> 
> Other jekyll theme is ok because I use jekyll theme minima before, everything is ok.

Thanks for your advice, I check it using browser network consule, and it seems that jquery-3.3.1.min.js cannot be loaded(it's red in the network console. I'm not familiar with website, but thought it may be the reason). I'll try to find more, thanks

**Comment by puppylpg** [comment]
Sorry to bother. It's exactly I can't visit `https://code.jquery.com/jquery-3.3.1.min.js` in my home(and using windows...). Try to download a jquery locally may solve the problem.
And thanks for your help

**Comment by vsoch** [comment]
Are you in China? I think various Google CDNs (and others) are blocked there? https://forum.jquery.com/topic/cannot-connect-to-google-cdn-from-china Really sorry :(

**Comment by puppylpg** [comment]
> Are you in China? I think various Google CDNs (and others) are blocked there? https://forum.jquery.com/topic/cannot-connect-to-google-cdn-from-china Really sorry :(

:D hahaha yeah, that's awkward. Anyways, thanks for your patience. I'll try a China jquery CDN or download jquery directly to use.

**Comment by vsoch** [comment]
Sounds good, let me know how it goes! If you find one that works, let's add a note to the documentation for future users that might run into this issue.

**Comment by puppylpg** [comment]
Here is what I do:
-  download jquery and put it into `assets/js`, aka `assets/js/jquery-3.3.1/jquery-3.3.1.js` and `assets/js/jquery-3.3.1/jquery-3.3.1.min.js`;
- find the places where jquery are used in project root: `grep -r "https://code.jquery.com/jquery-3.3.1.min.js" . --exclude-dir=_site`. they are `_include/head.html` and `_include/toc.html`；
- replace `src="https://code.jquery.com/jquery-3.3.1.min.js"` with `src="{{ site.baseurl }}/assets/js/jquery-3.3.1/jquery-3.3.1.min.js"`;

Everything works.

**Comment by vsoch** [comment]
@puppylpg if you'd like to open a PR with these changes (including the file for jquery with the repository) I'd be happy to review so that nobody else runs into this issue.

**Comment by puppylpg** [comment]
#26 Here it is

**Comment by vsoch** [comment]
Fixed with https://github.com/vsoch/docsy-jekyll/pull/26.
