### ISSUE TITLE
All the permalinks link back to https://vsoch.github.io/[permalink]

### ISSUE THREAD

**Issue by neotamias** [vsoch/docsy-jekyll#29]
as title says. I use this for my site and i've done some digging and still can't find why it's doing this. already changed my info in in the _config.yml

**Comment by neotamias** [comment]
scratch that, it just took a while for my page to get the update working :/ this is so embarassing :P

**Comment by vsoch** [comment]
No need to be embarrassed! It’s ok to ask for help and I’m glad you figured it out :)

**Comment by neotamias** [comment]
Yeah, I edited my config but forgot to CTL+F5 so I ended up getting the
cached page rather than the fresh one.
