### ISSUE TITLE
Issue with LICENSE.md

### ISSUE THREAD

**Issue by neotamias** [vsoch/docsy-jekyll#31]
Problematic line:
   Copyright [yyyy] [name of copyright owner]
Resolution:
Edit line to reflect owner's name and year of copyright

**Comment by vsoch** [comment]
That's the APPENDIX that shows how to apply the license to the work, it's not where (at least most that I see) put a year and copyright.  Since these are mostly html template files I'd be happy to add a COPYRIGHT notice file along with a single line in the site header.

**Comment by vsoch** [comment]
There you go! https://github.com/vsoch/docsy-jekyll/commit/d2b4027ecc31d85e2643b3fd5e8ec03d474e76be
