### ISSUE TITLE
Issue: _includes/google-analytics.html does not reference the _config.yml variable and is hardcoded, instead.

### ISSUE THREAD

**Issue by neotamias** [vsoch/docsy-jekyll#32]
Line 6\/\/
	ga('create', 'UA-00000000-0', 'auto');

**Comment by neotamias** [comment]
i'd fix this one but idk how it should be referenced for jekyll to pick it up right, sorry i wish i were more helpful here :/

**Comment by vsoch** [comment]
No worries - this is definitely a bug and thanks for pointing it out! It should now be fixed on master. https://github.com/vsoch/docsy-jekyll/commit/9abedb5aca09f8717f182adb9aa375207cb40400
