### ISSUE TITLE
Add multi-layerd drop downs in navigation menu

### ISSUE THREAD

**Issue by gregdegruy** [vsoch/docsy-jekyll#38]
Is it possible to create a navigation menu that's N layers deep? [The example](https://vsoch.github.io/docsy-jekyll/docs/getting-started#navigation) only shows a maximum of two drop downs items.
Like Documentation > Getting Started > Features.

I would like to create something like this
![image](https://user-images.githubusercontent.com/8151045/109741882-dede2f00-7b82-11eb-88db-ba93a066e51b.png)

**Comment by vsoch** [comment]
It's basically docsy in jekyll, so if it's not supported there, it's not supported here. https://example.docsy.dev/docs/. Note that smaller levels of navigation (on the page) appear in the right sidebar.

**Comment by gregdegruy** [comment]
Makes sense. Thanks for the detailed example page too. I have not seen that before.
