### ISSUE TITLE
Question: Tags are not working ?

### ISSUE THREAD

**Issue by akmohanta** [vsoch/docsy-jekyll#4]
Question on: https://github.com/vsoch/docsy-jekyll/tree/master/_docs/getting-started.md

Hey Vanessa,

is there a way to make the tags visible to these pages.

Thanks,
Anup

**Comment by vsoch** [comment]
Tags show up on the rendered jekyll page, and they are relevant for posts (see here) https://vsoch.github.io/docsy-jekyll/2019/hello-world/ could you better describe what you are trying to do?

**Comment by akmohanta** [comment]
I was just exploring about jekyll, and i came across this template of yours, as you have mentioned we could add external endpoint on tags for searching, i was trying that, but i am not getting how to do it.

Anyway no worries.
Thanks

**Comment by vsoch** [comment]
Ah, no this should work! Let me take a look. I might have just forgotten to add them to docs content.

**Comment by vsoch** [comment]
All set! https://vsoch.github.io/docsy-jekyll/docs/getting-started Thanks for pointing this out (I forgot to include it!) should be working properly now, and the readme image updated too :)

**Comment by akmohanta** [comment]
yeah, it's working now.
Cool :)
