### ISSUE TITLE
Indented sub titles

### ISSUE THREAD

**Issue by costaht** [vsoch/docsy-jekyll#45]
Wouldn't it be better if "User Interaction" and "Search" were indented under "Features" the same way "Features" is under "Getting Started"?

![Screenshot from 2021-06-04 01-23-37](https://user-images.githubusercontent.com/50637431/120749983-88f78b00-c4d3-11eb-8f87-c9c979a0e3e9.png)

**Comment by vsoch** [comment]
The implication is that user interaction and search are types of features.

**Comment by costaht** [comment]
Oh, I see. Thanks for the clarification.
