### ISSUE TITLE
Add support for webrick dependency or update readme.md to add guiding steps

### ISSUE THREAD

**Issue by akmalick** [vsoch/docsy-jekyll#48]
**Problem Statement :** `bundle exec jekyll serve` fails on Ruby 3+.

Error thrown :

`require': cannot load such file -- webrick (LoadError)`

**Expected :**
`bundle exec jekyll serve` should work fine and serve the site.

**Current workaround :** 

1. Execute `bundle add webrick` and then run `bundle exec jekyll serve`
2. Add `gem "webrick"` to the gemfile and run `bundle exec jekyll serve` 

**Possible solutions:**
- [ ] 1. Update the Gemfile with `gem "webrick"`
- [x] 2. Update the readme.md to highlight above two workarounds.

First Solution makes more sense to me as users of this project won't have to deal with the dependency themselves anymore, but it shouldn't hurt to update the **readme.md** file too along with it.

If this makes sense to all, I'll gladly raise the PR for Gemfile and ReadMe changes.

Similar discussion can be found here : https://github.com/jekyll/jekyll/issues/8523

**Comment by vsoch** [comment]
For now let’s add instructions for adding webrick given the build fails.

**Comment by akmalick** [comment]
Sounds good. I have included it as part of https://github.com/vsoch/docsy-jekyll/pull/49.

**Comment by vsoch** [comment]
Fixed with https://github.com/vsoch/docsy-jekyll/pull/49.
