### ISSUE TITLE
Guidelines for using docsy-jekyll in an enterprise project

### ISSUE THREAD

**Issue by akmalick** [vsoch/docsy-jekyll#50]
I see that this project is licensed under **Apache v2** which mean it is free to use/modify.
On the surface of it this license looks so simple. But once you read through it it tries to complicate things a bit like.
How should one use this theme for **company's internal projects** ?
What all things should one keep in mind **what modifications can be done** ?
The Apache v2 demands that the **license be carried forward** to the downstream derivate work. Does this carry forward of license bring in the **insecurity/fear of exposure of work** as far as usage in an **Enterprise** setup is concerned(as the derivative work is also containing Apache v2 license) ?

I believe Licensing is a topic that cannot be understood by just reading through it.  Let's agree License/Notices are not easy to understand.

**Comment by vsoch** [comment]
You generally need to carry forward the license for derivatives of the work. Maybe this helps? https://www.whitesourcesoftware.com/resources/blog/top-10-apache-license-questions-answered/

Yes agree licensing is hard to understand!

**Comment by akmalick** [comment]
Thanks for sharing. But I have browsed the whole of internet as far as this topic is concerned but every time I came across vague answers. Some answers came close to being complete, but none was actually complete and had an element of doubt in it.

If you could just list few specific things that I need to retain/ take care of that would be great. And I understand this is something which does not qualify for a valid request. But I really am very much into the ethics part.

> You generally need to carry forward the license for derivatives of the work. Maybe this helps? https://www.whitesourcesoftware.com/resources/blog/top-10-apache-license-questions-answered/

One one hand Answer to Question No. 8(**_How to Use Apache License 2.0 in commercial products?_**) says :
- You can use any Apache License 2.0 licensed software **in your commercial products for free**.

On the other hand it ducks the explanation in the very next paragraph :
-  While using Apache licensed software in your commercial product, you’re still required to follow the **terms and conditions that the Apache License imposes.**

**Comment by vsoch** [comment]
> If you could just list few specific things that I need to retain/ take care of that would be great. 

You need to keep the license and my attribution, e.g., you can't just delete those things. You can add (or extend) the attribution and the Copyright but you can't delete the original one, as I understand it.

> On the other hand it ducks the explanation in the very next paragraph :
> While using Apache licensed software in your commercial product, you’re still required to follow the terms and conditions that the Apache License imposes.

This isn't ducking anything, it says  you can use the software and you have to follow the rules of the license, which is what we just discussed. You can't, for example, delete the license and copyright entirely and plop some new one on it with someone else's name.

I'm not a lawyer, so if you have further questions I think you should probably reach out to one at your institution.

**Comment by akmalick** [comment]
> > If you could just list few specific things that I need to retain/ take care of that would be great.
> 
> You need to keep the license and my attribution, e.g., you can't just delete those things. You can add (or extend) the attribution and the Copyright but you can't delete the original one, as I understand it.

Got it. Short and simple.

> > On the other hand it ducks the explanation in the very next paragraph :
> > While using Apache licensed software in your commercial product, you’re still required to follow the terms and conditions that the Apache License imposes.
> 
> This isn't ducking anything, it says you can use the software and you have to follow the rules of the license, which is what we just discussed. You can't, for example, delete the license and copyright entirely and plop some new one on it with someone else's name.

I would still consider that as ducking 😄  because its kind of telling us please read and understand the license, whereas the whole point of answer in that article should have been to provide a clear/unambiguous and easy to understand explanation. Its like having a small asterisk at the very unimaginable place and saying **conditions apply**. As I said, I am very much into ethics and I believe licenses and copyright notices are best when it comes to doing justice to the efforts of individuals/organizations. I was just being curious.

> I'm not a lawyer, so if you have further questions I think you should probably reach out to one at your institution.

I believe people should be good as long as they keep the license and your attribution. Just wanted to know how it works in real world, hence the question. IANAL too. 😃 
Thanks 👏

**Comment by vsoch** [comment]
Sure thing! I don't have answers for most of your questions, as you said IANAL. But (from a people perspective) what I think is generally the right thing to do is to preserve original licenses, clearly link/point to them in the README, and also state the attribute. That is what I'd call good open source culture, to say "this work here is derived from this author, which is covered under this original license" (and then the reader can look at how you are sharing everything and determine if you are doing the right thing). I'm going to close this issue, thanks for the discussion!

**Comment by akmalick** [comment]
Thank you again.
