### ISSUE TITLE
Help-First Template Trial Problem

### ISSUE THREAD

**Issue by mccurcio** [vsoch/docsy-jekyll#53]
Dear Vanessa,
I am having problems with the first use of your docsy template. I have tried to use your template two ways.
1. by using "Use the template" button
2. by downloading the zip file
Both times the [mccurcio.github.io](https://mccurcio.github.io/) displays the svg icon on the front page out of proportion with the HTML.
I have tried changing the config.yml to fit my situation. It builds nicely and looks fine when I use my computer, etc. I am not sure where to look next.
This time I did nothing to limit the number of problems I introduced.
Any suggestions? 
I know you must be busy but I have tried beating my puny head and it really hurts. ;D
TY,
Matt

**Comment by vsoch** [comment]
A few things - if you are displaying on your github.io site, the baseurl should be empty here https://github.com/mccurcio/mccurcio.github.io/blob/fb520195ec5e217779da83750c0282ad65d209d3/_config.yml#L26. Then I'd look at the browser console and see if there are remaining script issues, etc.

**Comment by mccurcio** [comment]
YES, TY
I was confused by the line in config.yml
```
# DO NOT CHANGE THE LINE OF THIS FILE without editing .circleci/circle_urls.sh
```
I was not sure what to do there...
Thanks for the quick reply ;)

**Comment by vsoch** [comment]
oh yes! Sorry about that. That means "don't change the line number" - it's used in the preview. I can clarify that for the future. Thanks!
