### ISSUE TITLE
How to change text formatting

### ISSUE THREAD

**Issue by mccurcio** [vsoch/docsy-jekyll#54]
Greetings V,
I am trying to change the text formatting after code snippets are shown. I am using Python and would like to show the code result just below it. I know some put '#' hashes in front of the result in the code block but I would like to show RIGHT below. Where is the CSS for that aspect? Can you help?

![Let's try this pic](https://github.com/mccurcio/mccurcio/blob/main/try.to.change.text.formatting.png)

TY

**Comment by vsoch** [comment]
For any css element you can right click on the browser window -> inspect and then click on elements to see the exact style, and even add new styles dynamically to test out your ideas. That block in the browser shows the exact files and line numbers. For code blocks I would look out for code and pre.

**Comment by mccurcio** [comment]
You are a Gentle-Lady. ;)
