### ISSUE TITLE
Subfolder not viewable via 'A Nested Page'

### ISSUE THREAD

**Issue by mccurcio** [vsoch/docsy-jekyll#68]
Hi Vsoch,
I have a question about viewing the 'Subfolder` that is nested in your Docs. When I go to the 'A Nested Page' I am unable to go up one level to the subfolder by using the breadcrumbs. If you navigate to the link below and try the breadcrumbs you will find a 404. 
https://vsoch.github.io/docsy-jekyll/docs/subfolder/example-page

I would like to set my docsy site to be able to see the nested folders. I I would like to view the 'chapters'... Is that possible?
https://mccurcio.github.io/docs/chapters/logistic-regression-for-binary-classification
Was Docsy-J written with this in mind? or no? 
Any advice you have would be appreciated.
TY

**Comment by vsoch** [comment]
Yeah I think you'd need to try adding an index.md that renders to an index.html in that root.
