### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by michaeltryby** [vsoch/docsy-jekyll#71]
Hello! Thank you so much for your work on docsy-jekyll. It is wonderful and versioning is a killer feature! I am new to Jekyll and have run into a small problem getting the template project up and running. 

I cloned the repo and have Jekyll running locally. The docsy-jekyll template looks great, however, search is not working. Entering a term to search does nothing. 

I am running Chrome on Windows 10. When I run the site with Chrome in developer tools mode I see the following error: 
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:4000/docsy-jekyll/assets/js/jquery-3.3.1/jquery-3.3.1.min.js' with computed SHA-256 integrity 'T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4='. The resource has been blocked.
```
How can I fix this? Thanks!

**Comment by michaeltryby** [comment]
Here is a link to a similar issue in another repo ...

https://github.com/kubernetes/website/issues/25414

**Comment by vsoch** [comment]
You can either disable only having https for local development, use a different browser to do the same, or make some kind of self signed cert.

**Comment by vsoch** [comment]
Or you can try some of the suggestions there and if they work open a PR here.
