### ISSUE TITLE
CSS and javascript not loading

### ISSUE THREAD

**Issue by Capynetics** [vsoch/docsy-jekyll#77]
Hi!
I followed the tutorial under the usage section on the readme file but my website only displays the HTML, no CSS or JavaScript.
Please, take a look: https://uaibot.github.io/

**Comment by Capynetics** [comment]
Sorry, I am just stupid and added the website URL as baseurl on the _config.yml

**Comment by vsoch** [comment]
You aren't stupid! I'm glad you got it working!
